# Netlify configuration for React SPA with mobile optimizations

[build]
  # Build command for Vite with TypeScript
  command = "npm run build"
  # Output directory for Vite (usually 'dist')
  publish = "dist"
  # Ensure we use a compatible Node.js version
  environment = { NODE_VERSION = "18" }

# Build processing settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Redirect rules for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Mobile-optimized headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Mobile viewport and PWA support
    X-UA-Compatible = "IE=edge"
    
    # Performance headers for mobile
    X-DNS-Prefetch-Control = "on"
    
    # Mobile-friendly cache control
    Cache-Control = "public, max-age=0, must-revalidate"

# Optimize static assets for mobile
[[headers]]
  for = "/static/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    # Enable compression for mobile
    Content-Encoding = "gzip"

[[headers]]
  for = "/static/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = "gzip"

# Mobile image optimization
[[headers]]
  for = "/static/media/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    # Mobile-friendly image headers
    Vary = "Accept"

# Service Worker for PWA (mobile app-like experience)
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"

# Manifest file for mobile PWA
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400"

# Mobile-specific redirects for deep linking
[[redirects]]
  from = "/app/*"
  to = "/index.html"
  status = 200
  # Mobile app deep link handling
  conditions = {User-Agent = "*Mobile*"}

# Handle mobile share URLs
[[redirects]]
  from = "/share/*"
  to = "/index.html"
  status = 200

# Environment variables for mobile optimization
[context.production.environment]
  NODE_ENV = "production"
  VITE_MOBILE_OPTIMIZED = "true"
  # TypeScript build optimization
  TS_NODE_SKIP_IGNORE = "true"
  # Add your API URL here
  # VITE_API_URL = "https://your-api-domain.com"

# Development context
[context.deploy-preview.environment]
  NODE_ENV = "development"

# Branch-specific builds
[context.branch-deploy.environment]
  NODE_ENV = "development" 