# Netlify configuration for React SPA with client-side routing

[build]
  # Build command for Vite
  command = "npm run build"
  # Output directory for Vite (usually 'dist')
  publish = "dist"

# Redirect rules for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Optional: Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Optional: Environment variables (if needed)
# [context.production.environment]
#   NODE_ENV = "production"
#   REACT_APP_API_URL = "https://your-api-domain.com" 